### ISSUE TITLE
Translating words with macrons

### ISSUE THREAD

**Issue by cqb13** [Ethan-Winer/latin-web-app#1]
When trying to translate any word with a macron this error message is shown, "only letters, spaces, and commas are allowed". 
I would recommend creating a small function, perhaps something like this: 

const macronHandler = (str: string) => {
  return str
    .replace(/ā/g, "a")
    .replace(/ē/g, "e")
    .replace(/ī/g, "i")
    .replace(/ō/g, "o")
    .replace(/ū/g, "u");
};

this would remove macrons from the string that is inputted, allowing for easier copy and pasting words from a text that happen to have macrons, as the user would no longer have to remove them.

**Comment by Ethan-Winer** [comment]
Ik this is super late but i added something like that in
